spring:
  application:
    name: batchServer
  datasource:
    url: jdbc:mysql://localhost:3306/account_history
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_history
      username: root
      password: 1234
#      uri: ${SPRING_DATA_MONGODB_URI}
#      username: ${SPRING_DATA_MONGODB_USERNAME}
#      password: ${SPRING_DATA_MONGODB_PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
  sql:
    init:
      schema-locations: classpath:schema.sql

server:
  port: 8081
